# Generated by Django 5.1.6 on 2025-03-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
